MarioPizzeria/MarioPizzeria/Models/Pizza.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MarioPizzeria.Models
{
    public class Pizza
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [DisplayName("Pizza name")]
        [StringLength(30, MinimumLength = 3)]
        public string Name { get; set; }

        [Required]
        [Range(0, 1000)]
        [DataType(DataType.Currency)]
        [DisplayName("Price of small pizza")]
        public double PriceS { get; set; }

        [Required]
        [Range(0, 1000)]
        [DataType(DataType.Currency)]
        [DisplayName("Price of medium pizza")]
        public double PriceM { get; set; }

        [Required]
        [Range(0, 1000)]
        [DataType(DataType.Currency)]
        [DisplayName("Price of large pizza")]
        public double PriceL { get; set; }

        [Required]
        public string Crust { get; set; }

        public virtual ICollection<PizzaIngredient> PizzaIngredients { get; set; }
    }
}

MarioPizzeria/MarioPizzeria/Controllers/PizzaIngredientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MarioPizzeria.Data;
using MarioPizzeria.Models;

namespace MarioPizzeria.Controllers
{
    public class PizzaIngredientsController : Controller
    {
        private readonly PizzaDbContext _context;

        public PizzaIngredientsController(PizzaDbContext context)
        {
            _context = context;
        }

        // GET: PizzaIngredients
        public async Task<IActionResult> Index()
        {
            var pizzaDbContext = _context.PizzaIngredients.Include(p => p.Ingredient).Include(p => p.Pizza);
            return View(await pizzaDbContext.ToListAsync());
        }

        // GET: PizzaIngredients/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pizzaIngredient = await _context.PizzaIngredients
                .Include(p => p.Ingredient)
                .Include(p => p.Pizza)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pizzaIngredient == null)
            {
                return NotFound();
            }

            return View(pizzaIngredient);
        }

        // GET: PizzaIngredients/Create


        public IActionResult Create(int id)
        {
            ViewData["IngredientId"] = new SelectList(_context.Ingredients, "Id", "Name");
            var ingredients = _context.Ingredients.OrderBy(i=>i.Name).ToList();
            var selects = new List<IngredientCheckbox>();
            foreach (Ingredient ingredient in ingredients){
                bool isOnPizza = _context.PizzaIngredients.Where(pi => pi.PizzaId == id && pi.IngredientId == ingredient.Id).Any();
                selects.Add(new IngredientCheckbox(ingredient.Id, ingredient.Name, isOnPizza));
            }
           
            ViewData["PizzaId"] = new SelectList(_context.Pizzas.Where(x=> x.Id==id), "Id", "Name");
            ViewData["Ingredients"] = selects;
            return View();
        }

        // POST: PizzaIngredients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int PizzaId, List<int> NewIngredients)
        {
            if(ModelState.IsValid)
            {
                var oldIngredients = _context.PizzaIngredients.Where(m => m.PizzaId == PizzaId).Select(m => m.IngredientId).ToList();
                List<int> deleteIngredientsIds = oldIngredients.Except(NewIngredients).ToList();
                List<PizzaIngredient> toDelete = _context.PizzaIngredients.Where(m => m.PizzaId == PizzaId && deleteIngredientsIds.Contains(m.IngredientId)).ToList();
                List<int> addIngredientsIds = NewIngredients.Except(oldIngredients).ToList();
                List<PizzaIngredient> toAdd = new List<PizzaIngredient>();
                foreach (int i in addIngredientsIds)
                    toAdd.Add(new PizzaIngredient { PizzaId = PizzaId, IngredientId = i });

                _context.RemoveRange(toDelete);
                _context.AddRange(toAdd);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index","Pizzas");
            }
            ViewData["PizzaId"] = new SelectList(_context.Pizzas.Where(x => x.Id == PizzaId), "Id", "Name");
            return View();
        }

        // GET: PizzaIngredients/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pizzaIngredient = await _context.PizzaIngredients.FindAsync(id);
            if (pizzaIngredient == null)
            {
                return NotFound();
            }
            ViewData["IngredientId"] = new SelectList(_context.Ingredients, "Id", "Name", pizzaIngredient.IngredientId);
            ViewData["PizzaId"] = new SelectList(_context.Pizzas, "Id", "Name", pizzaIngredient.PizzaId);
            return View(pizzaIngredient);
        }

        // POST: PizzaIngredients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PizzaId,IngredientId")] PizzaIngredient pizzaIngredient)
        {
            if (id != pizzaIngredient.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pizzaIngredient);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PizzaIngredientExists(pizzaIngredient.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IngredientId"] = new SelectList(_context.Ingredients, "Id", "Name", pizzaIngredient.IngredientId);
            ViewData["PizzaId"] = new SelectList(_context.Pizzas, "Id", "Crust", pizzaIngredient.PizzaId);
            return View(pizzaIngredient);
        }

        // GET: PizzaIngredients/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pizzaIngredient = await _context.PizzaIngredients
                .Include(p => p.Ingredient)
                .Include(p => p.Pizza)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pizzaIngredient == null)
            {
                return NotFound();
            }

            return View(pizzaIngredient);
        }

        // POST: PizzaIngredients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pizzaIngredient = await _context.PizzaIngredients.FindAsync(id);
            _context.PizzaIngredients.Remove(pizzaIngredient);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PizzaIngredientExists(int id)
        {
            return _context.PizzaIngredients.Any(e => e.Id == id);
        }
    }
}

MarioPizzeria/MarioPizzeria/Controllers/PizzasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MarioPizzeria.Data;
using MarioPizzeria.Models;

namespace MarioPizzeria.Controllers
{
    public class PizzasController : Controller
    {
        private readonly PizzaDbContext _context;

        public PizzasController(PizzaDbContext context)
        {
            _context = context;
        }

        // GET: Pizzas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Pizzas.ToListAsync());
        }

        public async Task<IActionResult> Search(string SearchText)
        {
            Console.WriteLine(SearchText);
            var pizzas = _context.Pizzas;
            var pizzasList = await pizzas.ToListAsync();
            if (!string.IsNullOrEmpty(SearchText))
            {
                var filtered = pizzas.Where(pizza => pizza.Name.StartsWith(SearchText));
                if (filtered.Any())
                    pizzasList = await filtered.ToListAsync();
            }

            return View("Index", pizzasList);
        }

        // GET: Pizzas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pizza = await _context.Pizzas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pizza == null)
            {
                return NotFound();
            }

            var listOfIngredients = await _context.PizzaIngredients.Where(x => x.PizzaId == id).Select(x => x.Ingredient.Name).ToListAsync();
            ViewBag.PizzaIngredients = listOfIngredients;
            return View(pizza);
        }

        // GET: Pizzas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pizzas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,PriceS,PriceM,PriceL,Crust")] Pizza pizza)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pizza);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pizza);
        }

        // GET: Pizzas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pizza = await _context.Pizzas.FindAsync(id);
            if (pizza == null)
            {
                return NotFound();
            }
            return View(pizza);
        }

        // POST: Pizzas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,PriceS,PriceM,PriceL,Crust")] Pizza pizza)
        {
            if (id != pizza.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pizza);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PizzaExists(pizza.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pizza);
        }

        // GET: Pizzas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pizza = await _context.Pizzas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pizza == null)
            {
                return NotFound();
            }

            return View(pizza);
        }

        // POST: Pizzas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pizza = await _context.Pizzas.FindAsync(id);
            _context.Pizzas.Remove(pizza);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PizzaExists(int id)
        {
            return _context.Pizzas.Any(e => e.Id == id);
        }
    }
}

MarioPizzeria/MarioPizzeria/Views/Pizzas/Create.cshtml
@model MarioPizzeria.Models.Pizza

@{
    ViewData["Title"] = "Create";

    var crustList = new SelectList(
       new List<SelectListItem>
       {
            new SelectListItem {Text = "Thin", Value = "Thin"},
            new SelectListItem {Text = "Thick", Value = "Thick"},
       }, "Value", "Text");
}

<h1>New pizza</h1>
<hr/>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PriceS" class="control-label"></label>
                <input asp-for="PriceS" class="form-control" />
                <span asp-validation-for="PriceS" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PriceM" class="control-label"></label>
                <input asp-for="PriceM" class="form-control" />
                <span asp-validation-for="PriceM" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PriceL" class="control-label"></label>
                <input asp-for="PriceL" class="form-control" />
                <span asp-validation-for="PriceL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Crust" class="control-label"></label>
                @Html.DropDownListFor(m => m.Crust, crustList, "Select crust", new { @class = "form-control" })
                <span asp-validation-for="Crust" class="text-danger"></span>

            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("Index")'">Back to list</button>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MarioPizzeria/MarioPizzeria/Views/Pizzas/Delete.cshtml
@model MarioPizzeria.Models.Pizza

@{
    ViewData["Title"] = "Delete";
}

<h2>Are you sure you want to delete this pizza?</h2>
<hr />
<div>
    <h1>
        <b>
            @Html.DisplayFor(model => model.Name)
        </b>
    </h1>
    <hr />
    <dl class="row">
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.PriceS)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.PriceS)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.PriceM)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.PriceM)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.PriceL)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.PriceL)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Crust)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Crust)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <button type="button" style="margin-left:20px" class="btn btn-info" onclick="location.href='@Url.Action("Index")'">Back to list</button>
    </form>
</div>

MarioPizzeria/MarioPizzeria/Views/Pizzas/Details.cshtml
@model MarioPizzeria.Models.Pizza

@{
    ViewData["Title"] = "Details";
}

    <h1>@Model.Name</h1><div>
    <hr/>
    <h6><b>@Html.DisplayNameFor(model => model.PriceS)</b>: @Model.PriceS.ToString("c")</h6>
    <h6><b>@Html.DisplayNameFor(model => model.PriceM)</b>: @Model.PriceM.ToString("c")</h6>
    <h6><b>@Html.DisplayNameFor(model => model.PriceL)</b>: @Model.PriceL.ToString("c")</h6>
    <h6><b>@Html.DisplayNameFor(model => model.Crust)</b>: @Model.Crust</h6>
    <h6><b>Toppings</b></h6>
    <ul>
        @foreach (var ingredient in ViewBag.PizzaIngredients)
        {
            <li>@ingredient</li>
        }
    </ul>
</div>
<div>
    <button type="button" style="width:75px" class="btn btn-info" onclick="location.href='@Url.Action("Edit", new {id=Model.Id })'">Edit</button>
    <button type="button" style="margin-left:20px" class="btn btn-info" onclick="location.href='@Url.Action("Index")'">Back to list</button>
</div>

MarioPizzeria/MarioPizzeria/Views/Pizzas/Edit.cshtml
@model MarioPizzeria.Models.Pizza

@{
    ViewData["Title"] = "Edit";
    var crustList = new SelectList(
       new List<SelectListItem>
       {
                new SelectListItem {Text = "Thin", Value = "Thin"},
                new SelectListItem {Text = "Thick", Value = "Thick"},
       }, "Value", "Text");
}

<h1>Edit</h1>

<h4>Pizza</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PriceS" class="control-label"></label>
                <input asp-for="PriceS" class="form-control" />
                <span asp-validation-for="PriceS" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PriceM" class="control-label"></label>
                <input asp-for="PriceM" class="form-control" />
                <span asp-validation-for="PriceM" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PriceL" class="control-label"></label>
                <input asp-for="PriceL" class="form-control" />
                <span asp-validation-for="PriceL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Crust" class="control-label"></label>
                @Html.DropDownListFor(m => m.Crust, crustList, "Select crust", new { @class = "form-control" })

            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("Create", "PizzaIngredients", new {id=@Model.Id })'">Ingredients</button>
    
    <button type="button" style="margin-left:15px" class="btn btn-info" onclick="location.href='@Url.Action("Index")'">Back to list</button>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MarioPizzeria/MarioPizzeria/Views/Pizzas/Index.cshtml
@model IEnumerable<MarioPizzeria.Models.Pizza>

@{
    ViewData["Title"] = "Index";
}

<h1>Pizzas</h1>
<p>
    <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Create")'">Add new</button>
</p>
<form asp-action="Search">
    <div class="form-horizontal">
        <div class="form-group">
            <hr/>
            <div class="col-md-12">
                <input id="SearchText" name="SearchText" placeholder="Type pizza to search for ..." type="text" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                <input type="submit" value="Search" class="btn btn-info" />
            </div>
        </div>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PriceS)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PriceM)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PriceL)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Crust)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PriceS)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PriceM)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PriceL)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Crust)
            </td>
            <td>
                <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("Create", "PizzaIngredients", new {id=@item.Id })'">Ingredients</button>

                <button type="button" style="margin-left:15px; width:75px" class="btn btn-info" onclick="location.href='@Url.Action("Edit", new {id=@item.Id })'">Edit</button>
                <button type="button" style="margin-left:15px; width:75px" class="btn btn-info" onclick="location.href='@Url.Action("Details", new {id=@item.Id })'">Details</button>
                <button type="button" style="margin-left:15px; width:75px" class="btn btn-danger" onclick="location.href='@Url.Action("Delete", new {id=@item.Id })'">Delete</button>
            </td>
        </tr>
        }
    </tbody>
</table>